name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
      - name: Run and collect coverage for sender
        run: |
          coverage run --branch sender.test.py
          coverage html
          coverage report
      - name: Upload coverage for sender
        uses: actions/upload-artifact@v2
        with:
          name: coverageSender
          path: ./htmlcov
          retention-days: 21
      - name: Run and collect coverage for receiver
        run: |
          coverage run --branch receiver.test.py
          coverage html
          coverage report
      - name: Upload coverage for sender
        uses: actions/upload-artifact@v2
        with:
          name: coverageReceiver
          path: ./htmlcov
          retention-days: 21
      - name: run console redirection and pipes
        run: python sender.py | python receiver.py
      - name: run sender.test.py
        run: python sender.test.py
      - name: run receiver.test.py
        run: python receiver.test.py
